version: "3.8"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: fruits
    ports:
      - "3306:3306" # พอร์ตที่ MySQL ใช้งาน
    volumes:
      - mysql-data: /var/lib/mysql
volumes:
  mysql-data:
