version: "3.8"
services:
  fe:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Map port 8080 ของโฮสต์ไปยัง container
    volumes:
      - .:/app # Mount โฟลเดอร์โปรเจกต์เข้าไปใน container
      - /app/node_modules # ไม่ mount node_modules เพื่อป้องกันปัญหา dependency
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
    container_name: fe_dev
