version: "3.8"
services:
  fe:
    image: my-frontend-app
    build:
      context: . # ใช้ Dockerfile ในโฟลเดอร์ปัจจุบัน
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Map port 8080 ของโฮสต์ไปยัง container
