@host = https://identity.frappet.synology.me
@token = eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ3V0V6aG94dGFBTTV6b3JpWFVYdF9fbUExcTdkX0o3cDZXYUh0ZGk2bUR3In0.eyJleHAiOjE3MzYyMjc5MTMsImlhdCI6MTczNjIyMDcxMywianRpIjoiOGE5Mzg1YzYtZjIyMy00NzE2LWI4MTgtMGM5ODFkMTQ2Yjc2IiwiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5mcmFwcGV0LnN5bm9sb2d5Lm1lL3JlYWxtcy9tYXN0ZXIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJhZG1pbi1jbGkiLCJzaWQiOiI2OTQ0YzM2OS0wMmVkLTQ5ZjAtODg0Zi0wMTE1MjgzYjRmZTYiLCJzY29wZSI6InByb2ZpbGUgZW1haWwifQ.hwdaftRXMoQ4ObbWyDVPAOLXMeRKS96ePmjEvmcrLcHNzBJMwIC7NGAzLbtV3nw-I0uBM3V9EhDk6uIRKB7caqaYoto1tFoxaem8uvq-Tw8WHlfoP53RAlv19Rtjh-dSbih7WXowlnuWfXfqo04kKTzLewFqAZSeyf-C0pVBlouURbjfFWB5_94ulSXG9kINlpsu33-973YLHNslJF5DVAytu5bjEkBKd7D95eVCXtuLyRGnymv3YvYUzJxQCmsYvlelq5krYWgLXmfD40gvrw3D0qRvjpiNMkjGEey718UjxJEpt41XZiGbX0gaUSGCOxCV9PKzTMKcM0baRvc1sg




## public key of realm
GET {{host}}/realms/fluk-tiw
### Login for realms user
POST {{host}}/realms/fluk-tiw/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=express-client
&username=tiwly
&password=123
&grant_type=password

###
GET {{host}}/admin/realms/fluk-tiw/users
Authorization: Bearer {{token}}

########## Admin API https://www.keycloak.org/docs-api/latest/rest-api/index.html
## Login by admin of master realms
POST {{host}}/realms/master/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=admin-cli
&username=admin
&password=admin
&grant_type=password

### Login by secret of sso realms (server to server)
POST {{host}}/realms/fluk-tiw/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=b2b-client
&client_secret=yX9tg1EydPL55rB6Walu1ctXitstkcep
&grant_type=client_credentials

### default realms config
GET {{host}}/admin/realms
Authorization: Bearer {{token}}

### Get Realms config
GET {{host}}/admin/realms/fluk-tiw
Authorization: Bearer {{token}}

### Get users in realms
GET https://identity.frappet.synology.me/admin/realms/fluk-tiw/users
Authorization: Bearer {{token}}

### Create user in realms
POST {{host}}/admin/realms/fluk-tiw/users
Authorization: Bearer {{token}}

{
    "username":"fluk2",
    "email":"fluk2@aaa.com",
    "enabled":true,
    "credentials":[
        {
            "temporary":false,
            "type":"password",
            "value":"fluk2"
        }
    ]
}

### assign role not finished yet
POST {{host}}/admin/realms/sso/users/user_id/role-mappings/clients/client_uuid

### Get a user by name
GET {{host}}/admin/realms/sso/users/?username=oom
Authorization: Bearer {{token}}

### Delete user
DELETE {{host}}/admin/realms/sso/users/9144accb-ed90-461c-a00a-23aa02d2ef53
Authorization: Bearer {{token}}

### Find id of express-client
GET {{host}}/admin/realms/sso/clients/?clientId=express-client
Authorization: Bearer {{token}}

### Get role list in express-client
GET {{host}}/admin/realms/sso/clients/ea8ca0eb-f5f7-4843-a060-f0c263b30d26/roles
Authorization: Bearer {{token}}
